import Head from 'next/head'
import { Inter } from 'next/font/google'
import OnlyContent from './OnlyContent'
//
import style from './contents.module.scss'

const Contents = () => {
  return (
    <>
      <Head>
        <title>심리테스트</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={style.contents}>
        <OnlyContent />
      </div>
    </>
  )
}

export default Contents
