import Head from 'next/head'
import { Inter } from 'next/font/google'
//
import style from './onlyContent.module.scss'

const OnlyContent = () => {
  return (
    <>
      <Head>
        <title>심리테스트</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={style.content}>
        <header className={style.titleContainer}>
          <p>여행의 감성을 느끼기 위해 숙소를 예약했다.</p>
          <p>어떤 숙소였을까?</p>
        </header>
        <div className={style.btns}>
          <button>옵션 1</button>
          <button>옵션 2</button>
        </div>
        <div>
          <p>---------그래프 들어갈 예정----------</p>
        </div>
      </div>
    </>
  )
}

export default OnlyContent
